### ISSUE TITLE
Checking if users marked "remember me" checbkox and exists in database

### ISSUE THREAD

**Issue by danny3b** [narendravaghela/cakephp-remember-me#1]
I wonder how you handle that. In readme you wrote to put that in `beforeFilter()` callback. I couldn't make it work. 

I had to place following code in `public function initialize()`

```
$this->loadComponent('RememberMe.RememberMe');
$isRemembered = $this->RememberMe->getRememberedData();

    if($isRemembered != false) {
        $users= $this->Users = TableRegistry::get('Users');
        $remembered_user = $this->Users->findByUsername($isRemembered);
        $remembered_user = $remembered_user->first();
        $remembered_user = $remembered_user->toArray();

        if ($remembered_user) {
            $this->Auth->setUser($remembered_user);
        } else {
            $this->RememberMe->removeRememberedData();
        }
    }
```

And it's working fine, but maybe there is more elegant way to accomplish that?

**Comment by narendravaghela** [comment]
It should work in beforeFilter as well! I will check and revert with outcome.

**Comment by narendravaghela** [comment]
@danny3b Actually I have created this component and plugin for learning purpose and it is based on CakePHP 2.x version. But you can use same methods in CakePHP 3.x as well.

In Cake 3, load this component in `initialize()` method and check for data from Cookie in your AppController's `beforeFilter()`. If you find data from Cookie, set the user and mark it as logged in otherwise redirect it to login page. Please exclude your login action from the redirection.

For better implementation, use Component's callback methods to handle this e.g. check Cookie in your Component's `beforeFilter()` or `startup()` callback methods and either redirect user to login page or set the user session if cookies are valid. 

See doc here - http://book.cakephp.org/3.0/en/controllers.html#controller-callback-methods and http://book.cakephp.org/3.0/en/controllers/components.html#component-callbacks
